version: "3.9"

services:
    app:
        image: node:14-alpine
        command: >
                sh -c "
                apk add --no-cache git python3 make &&
                npm install &&
                npm start
                "
        ports:
            - 8080:8080
        working_dir: /app
        volumes:
            - ./:/app
            - discord-bot-db:/etc/discord-bot

volumes:
    discord-bot-db:
