name: backstage

on:
  push:
    branches:
      - backstage

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Build
        run: docker build --tag tracer1337/wolfgang:wolfgang-backstage .

      - name: Docker Push
        run: |
          docker login --username tracer1337 --password ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          docker push tracer1337/wolfgang:wolfgang-backstage

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Login
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker login --username tracer1337 --password ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Docker Remove
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker rm -f wolfgang-backstage
            docker rmi -f tracer1337/wolfgang:wolfgang-backstage
          
      - name: Docker Run
        uses: appleboy/ssh-action@v0.1.4
        env:
          STAGE_DISCORD_BOT_HOST: backstage.wolfgang.gg
          STAGE_DISCORD_BOT_PUBLIC_PORT: "443"
          STAGE_DISCORD_BOT_PROTOCOL: https
          STAGE_DISCORD_BOT_PORT: "8400"
          STAGE_DATABASE_HOST: host.docker.internal
          STAGE_DATABASE_PORT: "3306"
          STAGE_DATABASE_NAME: wolfgang-backstage
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: |
            STAGE_DISCORD_BOT_HOST,
            STAGE_DISCORD_BOT_PUBLIC_PORT,
            STAGE_DISCORD_BOT_PROTOCOL,
            STAGE_DISCORD_BOT_PORT,
            STAGE_DATABASE_HOST,
            STAGE_DATABASE_PORT,
            STAGE_DATABASE_NAME
          script: |
            docker run \
              --name wolfgang-backstage \
              --detach \
              --publish $STAGE_DISCORD_BOT_PORT:8080 \
              --network wolfgang-backstage \
              --add-host host.docker.internal:host-gateway \
              --restart=always \
              --env DISCORD_BOT_TOKEN=${{ secrets.STAGE_DISCORD_BOT_TOKEN }} \
              --env DISCORD_API_CLIENT_ID=${{ secrets.STAGE_DISCORD_API_CLIENT_ID }} \
              --env DISCORD_API_CLIENT_SECRET=${{ secrets.STAGE_DISCORD_API_CLIENT_SECRET }} \
              --env JWT_SECRET=${{ secrets.STAGE_JWT_SECRET }} \
              --env HOST=$STAGE_DISCORD_BOT_HOST \
              --env PUBLIC_PORT=$STAGE_DISCORD_BOT_PUBLIC_PORT \
              --env PROTOCOL=$STAGE_DISCORD_BOT_PROTOCOL \
              --env DATABASE_HOST=$STAGE_DATABASE_HOST \
              --env DATABASE_PORT=$STAGE_DATABASE_PORT \
              --env DATABASE_USER=${{ secrets.STAGE_DATABASE_USER }} \
              --env DATABASE_PASSWORD=${{ secrets.STAGE_DATABASE_PASSWORD }} \
              --env DATABASE_NAME=$STAGE_DATABASE_NAME \
              tracer1337/wolfgang:wolfgang-backstage
