name: deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: @actions/checkout@v2
      - name: Docker Build
        run: |
          docker build \
            --build-arg DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }} \
            --build-arg DISCORD_API_CLIENT_ID=${{ secrets.DISCORD_API_CLIENT_ID }} \
            --build-arg DISCORD_API_CLIENT_SECRET=${{ secrets.DISCORD_API_CLIENT_SECRET }} \
            --build-arg JWT_SECRET=${{ secrets.JWT_SECRET }} \
            --build-arg ADMIN_USER_IDS=${{ secrets.ADMIN_USER_IDS }} \
            --build-arg HOST=${{ secrets.HOST }} \
            --build-arg PROTOCOL=${{ secrets.PROTOCOL }} \
            --build-arg PUBLIC_PORT=${{ secrets.PUBLIC_PORT }} \
            --tag tracer1337/discord-bot:discord-bot \
            .
