name: production

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Build
        run: docker build --tag tracer1337/discord-bot:discord-bot .

      - name: Docker Push
        run: |
          docker login --username tracer1337 --password ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          docker push tracer1337/discord-bot:discord-bot

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Login
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker login --username tracer1337 --password ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Docker Remove
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker rm -f discord-bot
            docker rmi -f tracer1337/discord-bot:discord-bot
          
      - name: Docker Run
        uses: appleboy/ssh-action@v0.1.4
        env:
          DISCORD_BOT_HOST: v2202104145753149514.ultrasrv.de
          DISCORD_BOT_PUBLIC_PORT: "3100"
          DISCORD_BOT_PROTOCOL: http
          DISCORD_BOT_PORT: "8300"
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: DISCORD_BOT_HOST,DISCORD_BOT_PUBLIC_PORT,DISCORD_BOT_PROTOCOL,DISCORD_BOT_PORT
          script: |
            docker run \
              --name discord-bot \
              --detach \
              --publish $DISCORD_BOT_PORT:8080 \
              --volume discord-bot:/etc/storage \
              --network discord-bot \
              --restart=always \
              --env DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }} \
              --env DISCORD_API_CLIENT_ID=${{ secrets.DISCORD_API_CLIENT_ID }} \
              --env DISCORD_API_CLIENT_SECRET=${{ secrets.DISCORD_API_CLIENT_SECRET }} \
              --env JWT_SECRET=${{ secrets.JWT_SECRET }} \
              --env ADMIN_USER_IDS=${{ secrets.ADMIN_USER_IDS }} \
              --env HOST=$DISCORD_BOT_HOST \
              --env PUBLIC_PORT=$DISCORD_BOT_PUBLIC_PORT \
              --env PROTOCOL=$DISCORD_BOT_PROTOCOL \
              tracer1337/discord-bot:discord-bot
